development:
  adapter: mysql2
  encoding: utf8
  database: giv2giv_development
  host: localhost
  username: giv2giv
  password: giv2giv

test:
  adapter: mysql2
  encoding: utf8
  database: giv2giv_test
  host: localhost
  username: giv2giv
  password: giv2giv

production:
  adapter: mysql2
  encoding: utf8
  database: giv2giv_production
  host: localhost
  username: giv2giv
  password: giv2giv
